language: java
matrix:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk8
  - os: osx
    osx_image: xcode9.3
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: jm0XPp+DIgfmdDRqDeLo/5oL0lqyr6cPL8AGXjozgeP2rqwX4mvkY9XfuVJsJs38EY98op/hgxmX6WPssq7LoyWs4i/nsmkxTGxVRQaPd1ndGtKTet/c3loTJ6LaP+ssb57LTOvX28UVcCAukPB1XJ3yKeQexw0hPCz67JNhb/k=
  - secure: eu29iTOPfLgpGur/hLL5D2SfMdbVn6e2RwXVrr136CuuNkOZh6dTz3ogOXfmoCnYvAM/QYll/p5B1Gjb0UZIxyzPkLtFdRMd/idUoTFBInlyVKaNjmbWUtEV4IMj2sVHizKsbYPC377ogpv4EjF9XABVzeSzrarSs0st7O1ZxNo=
  - secure: XM95UxqKiQ+3aaMJvkFHaAlKBnJ94oK9xZr51f/Vh4yF9+K1jB7MlSs28KF7TZuBfdv7Pjryh9ogCBQOdhiOZvw4y1TzyNRc4eZgKCoZTsmMlTcbUmJ50hmZN/O9Nh0qRXCcp1EuIYQYQYJbnEzjoN6S+TeMFb76Qq4b/3jW63w=
  - secure: Xq5Mqc8q0USazrEfsAOHHt85cxMMcK5Ck3YGy61k50PmFiJFJ6PuFKZxKc8UVtgI9OU/Qpb1UUI6Ow0XZ1nCmYkC3A3BVAl/stSxKcNeFPRHxkxIOcBBCrzow7JFB3Fxoo57PbRvUiN0bDgT/XHWJvOUIQjdNDABngKyetf587A=
