version: '{build}'
clone_depth: 10

branches:
  only:
    - master
    - /.*-[0-9]+\..*/

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0\
  GNUPG_HOME: C:\Gpg4win\
  MAVEN_BIN: C:\Program Files (x86)\Apache\Maven\bin\
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  GIT_BIN: C:\Program Files\Git\bin\
  CMAKE_BIN: C:\Program Files (x86)\CMake\bin\
  CERTIFICATE_KEY:
    secure: 8lYslVDOXaNTMGHpFSFVH40OzX70ofXnVW35qCNVkZvjHKJODVDwuGkndacv4hv7
  MAVEN_PASS:
    secure: YdzLF8dSsHb8PwXVy9buOI3lGhJ5ReexXDLvD34eJt1C9FXuf9o6oBX72GTc5Jgd
  GPG_KEY_NAME:
    secure: xyRp14pV2TD4fYfi35GfksuJ1I1Wk/5nIEo0F6zB3H8=
  GPG_PASSPHRASE:
    secure: gTrK/G3QiaY3zP8fanCshlU9beRK/4tPvzeylGd+kL2v5BmaisUZFlhKNEWCO1Bm
  CI: true

cache:
  - C:\Users\appveyor\.m2\repository
  - C:\gpg4win-vanilla-2.3.4.exe

image: Visual Studio 2015

platform:
  - x86
  - x64

install:
  - ps: .\.appveyor\setup.ps1

build_script:
  - ps: .\.appveyor\build.ps1
